//  Copyright (c) 2014 Grant Mercer
//  Copyright (c) 2014-2023 Hartmut Kaiser
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

/// \file parallel/container_algorithms/generate.hpp
/// \page hpx::ranges::generate, hpx::ranges::generate_n
/// \headerfile hpx/algorithm.hpp

#pragma once

#if defined(DOXYGEN)
namespace hpx { namespace ranges {
    // clang-format off

    /// Assign each element in range [first, last) a value generated by the
    /// given function object f
    ///
    /// \note   Complexity: Exactly \a distance(first, last)
    ///                     invocations of \a f and assignments.
    ///
    /// \tparam Rng         The type of the source range used (deduced).
    ///                     The iterators extracted from this range type must
    ///                     meet the requirements of an forward iterator.
    /// \tparam F           The type of the function/function object to use
    ///                     (deduced). Unlike its sequential form, the parallel
    ///                     overload of \a equal requires \a F to meet the
    ///                     requirements of \a CopyConstructible.
    ///
    /// \param rng          Refers to the sequence of elements the algorithm
    ///                     will be applied to.
    /// \param f            generator function that will be called. signature of
    ///                     function should be equivalent to the following:
    ///                     \code
    ///                     Ret fun();
    ///                     \endcode \n
    ///                     The type \a Ret must be such that an object of type
    ///                     \a FwdIter can be dereferenced and assigned a value
    ///                     of type \a Ret.
    ///
    /// \returns  The \a replace_if algorithm returns \a last.
    ///
    template <typename Rng, typename F>
    std::ranges::iterator_t<Rng>
    generate(Rng&& rng, F&& f);

    /// Assign each element in range [first, last) a value generated by the
    /// given function object f
    ///
    /// \note   Complexity: Exactly \a distance(first, last)
    ///                     invocations of \a f and assignments.
    ///
    /// \tparam Iter        The type of the source begin iterator used (deduced).
    ///                     This iterator type must meet the requirements of an
    ///                     forward iterator.
    /// \tparam Sent        The type of the source end iterator used (deduced).
    ///                     This iterator type must meet the requirements of an
    ///                     forward iterator.
    /// \tparam F           The type of the function/function object to use
    ///                     (deduced). Unlike its sequential form, the parallel
    ///                     overload of \a equal requires \a F to meet the
    ///                     requirements of \a CopyConstructible.
    ///
    /// \param first        Refers to the beginning of the sequence of elements
    ///                     the algorithm will be applied to.
    /// \param last         Refers to the end of the sequence of elements the
    ///                     algorithm will be applied to.
    /// \param f            generator function that will be called. signature of
    ///                     function should be equivalent to the following:
    ///                     \code
    ///                     Ret fun();
    ///                     \endcode \n
    ///                     The type \a Ret must be such that an object of type
    ///                     \a FwdIter can be dereferenced and assigned a value
    ///                     of type \a Ret.
    ///
    /// \returns  The \a replace_if algorithm returns \a last.
    ///
    template <typename Iter, typename Sent, typename F>
    Iter generate(Iter first, Sent last, F&& f);

    /// Assigns each element in range [first, first+count) a value generated by
    /// the given function object g.
    ///
    /// \note   Complexity: Exactly \a count invocations of \a f and
    ///         assignments, for count > 0.
    ///
    /// \tparam FwdIter     The type of the source iterators used (deduced).
    ///                     This iterator type must meet the requirements of an
    ///                     forward iterator.
    /// \tparam Size        The type of the argument specifying the number of
    ///                     elements to apply \a f to.
    /// \tparam F           The type of the function/function object to use
    ///                     (deduced). Unlike its sequential form, the parallel
    ///                     overload of \a equal requires \a F to meet the
    ///                     requirements of \a CopyConstructible.
    ///
    /// \param first        Refers to the beginning of the sequence of elements
    ///                     the algorithm will be applied to.
    /// \param count        Refers to the number of elements in the sequence the
    ///                     algorithm will be applied to.
    /// \param f            Refers to the generator function object that will be
    ///                     called. The signature of the function should be
    ///                     equivalent to
    ///                     \code
    ///                     Ret fun();
    ///                     \endcode \n
    ///                     The type \a Ret must be such that an object of type
    ///                     \a OutputIt can be dereferenced and assigned a value
    ///                     of type \a Ret.
    ///
    /// \returns  The \a replace_if algorithm returns \a last.
    ///
    template <typename FwdIter, typename Size, typename F>
    FwdIter generate_n(FwdIter first, Size count, F&& f);

    // clang-format on

    /// \brief Execution-policy overload of \c generate.
    /// \note Requires random access iterators and sized sentinels, or sized
    /// random access ranges. Callable and element requirements are expressed
    /// in the constraints below.
    /// \returns The algorithm result, wrapped in a future for task policies.
    /// Iterator and subrange results use the standard borrowed-range rules.
    /// A future does not extend the lifetime of the underlying range storage.
    template <typename ExPolicy, std::ranges::random_access_range R, typename F>
        requires hpx::is_execution_policy_v<ExPolicy> &&
        std::ranges::sized_range<R> && std::copy_constructible<F> &&
        std::invocable<F&> &&
        std::indirectly_writable<std::ranges::iterator_t<R>,
            std::invoke_result_t<F&>>
    parallel::util::detail::algorithm_result_t<ExPolicy,
        std::ranges::borrowed_iterator_t<R>>
    generate(ExPolicy&& policy, R&& rng, F f);

    /// \brief Execution-policy overload of \c generate.
    /// \note Requires random access iterators and sized sentinels, or sized
    /// random access ranges. Callable and element requirements are expressed
    /// in the constraints below.
    /// \returns The algorithm result, wrapped in a future for task policies.
    template <typename ExPolicy, std::random_access_iterator I,
        std::sized_sentinel_for<I> S, typename F>
        requires hpx::is_execution_policy_v<ExPolicy> &&
        std::copy_constructible<F> && std::invocable<F&> &&
        std::indirectly_writable<I, std::invoke_result_t<F&>>
    parallel::util::detail::algorithm_result_t<ExPolicy, I> generate(
        ExPolicy&& policy, I first, S last, F f);

    /// \brief Execution-policy overload of \c generate_n.
    /// \note Requires random access iterators and sized sentinels, or sized
    /// random access ranges. Callable and element requirements are expressed
    /// in the constraints below.
    /// \returns The algorithm result, wrapped in a future for task policies.
    template <typename ExPolicy, std::random_access_iterator I, typename F>
        requires hpx::is_execution_policy_v<ExPolicy> &&
        std::copy_constructible<F> && std::invocable<F&> &&
        std::indirectly_writable<I, std::invoke_result_t<F&>>
    parallel::util::detail::algorithm_result_t<ExPolicy, I> generate_n(
        ExPolicy&& policy, I first, std::iter_difference_t<I> count, F f);
}}    // namespace hpx::ranges

#else    //DOXYGEN

#include <hpx/config.hpp>
#include <hpx/modules/concepts.hpp>
#include <hpx/modules/iterator_support.hpp>
#include <hpx/parallel/algorithms/detail/tag_dispatch.hpp>
#include <hpx/parallel/algorithms/generate.hpp>

#include <algorithm>
#include <cstddef>
#include <functional>
#include <iterator>
#include <ranges>
#include <type_traits>
#include <utility>

namespace hpx::ranges {

    ///////////////////////////////////////////////////////////////////////////
    // CPO for hpx::ranges::generate
    HPX_CXX_CORE_EXPORT inline constexpr struct generate_t final
      : hpx::detail::tag_dispatch<generate_t,
            hpx::detail::tag_parallel_algorithm<generate_t>>
    {
        template <typename ExPolicy, std::ranges::random_access_range R,
            typename F>
            requires hpx::is_execution_policy_v<ExPolicy> &&
            std::ranges::sized_range<R> && std::copy_constructible<F> &&
            std::invocable<F&> &&
            std::indirectly_writable<std::ranges::iterator_t<R>,
                std::invoke_result_t<F&>>
        static decltype(auto) invoke_default(ExPolicy&& policy, R&& rng, F f)
        {
            using I = std::ranges::iterator_t<R>;
            auto first = std::ranges::begin(rng);
            return parallel::util::detail::convert_to_result(
                invoke_default(HPX_FORWARD(ExPolicy, policy), first,
                    first + std::ranges::distance(rng), HPX_MOVE(f)),
                [](I result) -> std::ranges::borrowed_iterator_t<R> {
                    return result;
                });
        }

        template <typename ExPolicy, std::random_access_iterator I,
            std::sized_sentinel_for<I> S, typename F>
            requires hpx::is_execution_policy_v<ExPolicy> &&
            std::copy_constructible<F> && std::invocable<F&> &&
            std::indirectly_writable<I, std::invoke_result_t<F&>>
        static decltype(auto) invoke_default(
            ExPolicy&& policy, I first, S last, F f)
        {
            auto end = first + (last - first);
            return parallel::detail::generate<I>().call(
                HPX_FORWARD(ExPolicy, policy), first, end, HPX_MOVE(f));
        }

        template <typename Rng, typename F>
            requires(std::ranges::range<Rng>)
        static std::ranges::iterator_t<Rng> invoke_default(Rng&& rng, F f)
        {
            using iterator_type = std::ranges::iterator_t<Rng>;

            static_assert(std::forward_iterator<iterator_type>,
                "Required at least forward iterator.");

            return hpx::parallel::detail::generate<iterator_type>().call(
                hpx::execution::seq, hpx::util::begin(rng), hpx::util::end(rng),
                HPX_MOVE(f));
        }

        template <typename Iter, typename Sent, typename F>
            requires(std::sentinel_for<Sent, Iter>)
        static Iter invoke_default(Iter first, Sent last, F f)
        {
            static_assert(std::forward_iterator<Iter>,
                "Required at least forward iterator.");

            return hpx::parallel::detail::generate<Iter>().call(
                hpx::execution::seq, first, last, HPX_MOVE(f));
        }
    } generate{};

    ///////////////////////////////////////////////////////////////////////////
    // CPO for hpx::ranges::generate_n
    HPX_CXX_CORE_EXPORT inline constexpr struct generate_n_t final
      : hpx::detail::tag_dispatch<generate_n_t,
            hpx::detail::tag_parallel_algorithm<generate_n_t>>
    {
        template <typename ExPolicy, std::random_access_iterator I, typename F>
            requires hpx::is_execution_policy_v<ExPolicy> &&
            std::copy_constructible<F> && std::invocable<F&> &&
            std::indirectly_writable<I, std::invoke_result_t<F&>>
        static decltype(auto) invoke_default(
            ExPolicy&& policy, I first, std::iter_difference_t<I> count, F f)
        {
            auto const size = (std::max) (std::iter_difference_t<I>(0), count);
            return parallel::detail::generate_n<I>().call(
                HPX_FORWARD(ExPolicy, policy), first,
                static_cast<std::size_t>(size), HPX_MOVE(f));
        }

        template <typename FwdIter, typename Size, typename F>
        // clang-format off
            requires(
                hpx::traits::is_iterator_v<FwdIter> &&
                std::is_integral_v<Size>
            )
        // clang-format on
        static FwdIter invoke_default(FwdIter first, Size count, F f)
        {
            static_assert(std::forward_iterator<FwdIter>,
                "Required at least forward iterator.");

            if (hpx::parallel::detail::is_negative(count))
            {
                return first;
            }

            return hpx::parallel::detail::generate_n<FwdIter>().call(
                hpx::execution::seq, first, static_cast<std::size_t>(count),
                HPX_MOVE(f));
        }
    } generate_n{};
}    // namespace hpx::ranges

#endif    // DOXYGEN
